name: flutter_note_app
description: Flutter Note App
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^3.26.0
  google_fonts: ^2.0.0
  sqflite: ^2.0.0+3
  flutter_staggered_grid_view: ^0.3.4
  intl: ^0.17.0
  numberpicker: ^2.1.1
  fancy_bottom_navigation: ^0.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/image.jpg

  fonts:
    - family: Shabnam
      fonts:
        - asset: assets/fonts/shabnam.ttf